toggle_function:
  name: function
  description: Function to Toggle
  target:
    entity:
      integration: irhumidifier
      domain: humidifier
  fields:
    function:
      name: Humidifier Function
      description: Toggle specified function on/off
      required: true
      selector:
        

  selector:
    select:
      options:
        - "light"
        - "uv"
        - "warm_mist"
        - "night_mode"
increase:
  name: increase
  description: Increase Speed/Humidity Setting
decrease:
  name: decrease
  description: Decrease Speed/Humidity Setting]
set_speed:
  name: set_speed
  description: Function to set speed
  required: true
  selector:
    select:
      number:
        min: 1
        max: 7
        step: 1
